Repository nextcloud/notes-android, pull requests merged in 2023-01, with the labels that each got.

#1646 Create command-rebase.yml
  .github/workflows/command-rebase.yml
Labels: meta, 3. to review

#1651 unify room dependency version
  app/build.gradle
Labels: technical debt

#1652 Bump room to 2.5.0
  app/build.gradle
Labels: dependencies, 3. to review, technical debt

#1655 Update maintainer and developer list in credits screen
  app/src/main/java/it/niedermann/owncloud/notes/about/AboutFragmentCreditsTab.java
  app/src/main/java/it/niedermann/owncloud/notes/shared/util/SupportUtil.java
  app/src/main/res/layout/fragment_about_credits_tab.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review
