Repository nextcloud/notes-android, pull requests merged in 2024-04, with the labels that each got.

#1904 Allow the user to disable direct-editing
  app/src/main/java/it/niedermann/owncloud/notes/edit/NoteEditFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/NotePreviewFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/SearchableBaseNoteFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/preferences/PreferencesFragment.java
  app/src/main/res/drawable/ic_rich_editing_grey600_24dp.xml
  app/src/main/res/layout/fragment_note_preview.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: feedback-requested

#2109 Bump com.github.stefan-niedermann.nextcloud-commons to 2.2.0
  app/build.gradle
  build.gradle
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: dependencies, 4. to release

#2115 Use FLAG_IMMUTABLE if needed
  app/src/main/java/it/niedermann/owncloud/notes/shared/util/WidgetUtil.java
Labels: backport-request

#2150 Improve codacy
  app/src/main/java/it/niedermann/owncloud/notes/NotesApplication.java
  app/src/main/java/it/niedermann/owncloud/notes/about/AboutActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/EditNoteActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/category/CategoryDialogFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/title/EditTitleDialogFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/main/MainActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/ItemAdapter.java
Labels: technical debt
