Repository nextcloud/notes-android, pull requests merged in 2024-01, with the labels that each got.

#1979 chore(deps): AGP 8, Java 17, Kotlin 1.9.22, SSO 1.0.0
  .github/workflows/android.yml
  .github/workflows/codeql.yml
  app/build.gradle
  app/src/main/java/it/niedermann/owncloud/notes/about/AboutActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/branding/BrandedActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/branding/BrandedFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/branding/BrandedSwitchPreference.java
  app/src/main/java/it/niedermann/owncloud/notes/branding/NotesViewThemeUtils.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/BaseNoteFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/EditNoteActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/SearchableBaseNoteFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/category/CategoryAdapter.java
  app/src/main/java/it/niedermann/owncloud/notes/exception/ExceptionActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/exception/ExceptionDialogFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/exception/tips/TipsAdapter.java
  app/src/main/java/it/niedermann/owncloud/notes/importaccount/ImportAccountActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/main/MainActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/main/MainViewModel.java
  app/src/main/java/it/niedermann/owncloud/notes/main/MultiSelectedActionModeCallback.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/ItemAdapter.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/NoteViewHolder.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/list/NotesListViewItemTouchHelper.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/section/SectionItem.java
  app/src/main/java/it/niedermann/owncloud/notes/main/navigation/NavigationItem.java
  app/src/main/java/it/niedermann/owncloud/notes/manageaccounts/ManageAccountsViewModel.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/ApiProvider.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesRepository.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesServerSyncTask.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/entity/Account.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/entity/CategoryOptions.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/entity/CategoryWithNotesCount.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/entity/Note.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/entity/NotesListWidgetData.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/entity/SingleNoteWidgetData.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/migration/Migration_20_21.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/sync/CapabilitiesDeserializer.java
  app/src/main/java/it/niedermann/owncloud/notes/shared/model/NavigationCategory.java
  app/src/main/java/it/niedermann/owncloud/notes/shared/util/NotesColorUtil.java
  app/src/main/java/it/niedermann/owncloud/notes/widget/AbstractWidgetData.java
  app/src/main/java/it/niedermann/owncloud/notes/widget/notelist/NoteListWidgetFactory.java
  app/src/test/resources/robolectric.properties
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: 3. to review

#1969 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
Labels: dependencies, 3. to review, automated, feedback-requested

#1995 Remove local dependency jar generic definition
  app/build.gradle
Labels: 2. developing

#1996 Add dependency checksums and signing key information
  .gitignore
  app/build.gradle
  gradle.properties
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review
