Repository nextcloud/notes-android, pull requests merged in 2024-05, with the labels that each got.

#2162 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#2161 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#2170 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#2183 Fix / Restrictions to Implicit and Pending intents (Widget Bugfix)
  app/src/main/java/it/niedermann/owncloud/notes/shared/util/WidgetUtil.java
  app/src/main/java/it/niedermann/owncloud/notes/widget/notelist/NoteListWidget.java
  app/src/main/java/it/niedermann/owncloud/notes/widget/notelist/NoteListWidgetFactory.java
Labels: 3. to review

#2189 bump to 4.3.0 RC1
  app/build.gradle
Labels: 4. to release

#2201 Stable 4.3 main update
  .github/workflows/codeql.yml
  .github/workflows/scorecard.yml
  Gemfile.lock
  app/build.gradle
  build.gradle
  gradle/verification-metadata.xml
Labels: 4. to release, technical debt

#2206 fix: Move to EmptyResponse instead off now unsupported Void
  app/src/main/java/it/niedermann/owncloud/notes/persistence/sync/NotesAPI.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/sync/NotesAPI_0_2.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/sync/NotesAPI_1_0.java
Labels: 4. to release, backport-request
