Repository nextcloud/notes-android, pull requests merged in 2024-07, with the labels that each got.

#2267 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#2270 Migrate REUSE to TOML format
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#2274 fix: give hint about missing server-side app for 404s
  app/src/main/java/it/niedermann/owncloud/notes/exception/tips/TipsAdapter.java
Labels: enhancement, 3. to review
