Repository nextcloud/notes-android, pull requests merged in 2024-03, with the labels that each got.

#2043 Add key and signature for dependency
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 4. to release, technical debt

#2046 Update GH templates with SPDX headers
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: technical debt

#2047 Update GH templates with SPDX headers
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md.license
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md.license
Labels: bug, technical debt

#2044 Initial adding of SPDX header and dep5 package description
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/android.yml
  .github/workflows/command-rebase.yml
  .github/workflows/pr-feedback.yml
  .gitignore
  .gitmodules
  .idea/.gitignore
  .reuse/dep5
  .tx/config.license
  CONTRIBUTING.md
  FAQ.md
  Gemfile.license
  Gemfile.lock.license
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/GPL-3.0-or-later.txt
  PRIVACY.md
  README.md
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_rich_editing.xml
  build.gradle
  fastlane/Appfile.license
  fastlane/Fastfile
  fastlane/common.Fastfile.license
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  scripts/analysis/analysis-wrapper.sh
  settings.gradle
Labels: 3. to review, technical debt

#2063 Optimize spdx scan
  .reuse/dep5
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+en+001/strings.xml
  app/src/main/res/values-bg-rBG/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs-rCZ/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es-rEC/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi-rFI/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu-rHU/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-is/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt-rLT/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sk-rSK/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  gradle/verification-keyring.keys.license
  gradle/verification-metadata.xml.license
  gradle/wrapper/gradle-wrapper.jar.license
  gradlew
  gradlew.bat
Labels: 3. to review, technical debt

#2088 Restrict export of app components.
  app/src/main/AndroidManifest.xml
Labels: backport-request
