Repository nextcloud/notes-android, pull requests merged in 2025-06, with the labels that each got.

#2663 docs(faq): Update TokenMismatchException answer with new knowledge about the cause
  FAQ.md
Labels: feedback-requested

#2682 4.4.0 RC1
  app/build.gradle
Labels: 3. to review

#2685 ci(chksm): Update meta-data
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 4. to release, technical debt

#2687 BugFix - Add missing migration 26
  REUSE.toml
  app/schemas/it.niedermann.owncloud.notes.persistence.NotesDatabase/23.json
  app/schemas/it.niedermann.owncloud.notes.persistence.NotesDatabase/25.json
  app/schemas/it.niedermann.owncloud.notes.persistence.NotesDatabase/26.json
  app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesDatabase.java
Labels: 3. to review, backport-request

#2693 bump to correct version 40040051
  app/build.gradle
Labels: 3. to review

#2694 Next Minor Version
  app/build.gradle
Labels: 3. to review
