Repository nextcloud/notes-android, pull requests merged in 2025-07, with the labels that each got.

#2697 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#2710 4.4.0 RC3
  app/build.gradle
Labels: 3. to review

#2711 Use star outline variant for non-favorite state representation
  app/src/main/java/it/niedermann/owncloud/notes/edit/BaseNoteFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/NoteViewHolder.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesRepository.java
  app/src/main/res/drawable/ic_star_border_grey_ccc_24dp.xml
Labels: 3. to review, design

#2713 General Bug-Fixes
  app/src/main/java/it/niedermann/owncloud/notes/branding/BrandedFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/branding/BrandedFragment.kt
  app/src/main/java/it/niedermann/owncloud/notes/edit/NoteDirectEditFragment.kt
  app/src/main/java/it/niedermann/owncloud/notes/edit/NoteEditFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/NotePreviewFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/DirectEditingRepository.kt
  app/src/main/java/it/niedermann/owncloud/notes/widget/notelist/NoteListWidgetFactory.java
Labels: 3. to review

#2714 BugFix - Set As Favorite
  app/src/main/java/it/niedermann/owncloud/notes/edit/BaseNoteFragment.java
  app/src/main/java/it/niedermann/owncloud/notes/main/MainActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/main/MainViewModel.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/list/NotesListViewItemTouchHelper.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesRepository.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/sync/NotesAPI.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/sync/NotesAPI_0_2.java
  app/src/main/java/it/niedermann/owncloud/notes/persistence/sync/NotesAPI_1_0.java
  gradle/verification-metadata.xml
Labels: 3. to review, backport-request

#2724 4.4.0
  app/build.gradle
Labels: 3. to review

#2737 BugFix - Widget Crash
  app/src/main/AndroidManifest.xml
  app/src/main/java/it/niedermann/owncloud/notes/widget/notelist/NoteListWidget.java
  app/src/main/java/it/niedermann/owncloud/notes/widget/notelist/NoteListWidget.kt
  app/src/main/java/it/niedermann/owncloud/notes/widget/notelist/NoteListWidgetFactory.java
  app/src/main/java/it/niedermann/owncloud/notes/widget/notelist/NoteListWidgetFactory.kt
  app/src/main/java/it/niedermann/owncloud/notes/widget/singlenote/SingleNoteWidget.java
  app/src/main/java/it/niedermann/owncloud/notes/widget/singlenote/SingleNoteWidget.kt
  app/src/main/res/layout/widget_entry.xml
  app/src/main/res/layout/widget_note_list.xml
Labels: 3. to review, backport-request

#2729 🎨 Update Material Design to be more M3
  app/src/main/java/it/niedermann/owncloud/notes/FormattingHelpActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/about/AboutActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/branding/NotesViewThemeUtils.java
  app/src/main/java/it/niedermann/owncloud/notes/edit/EditNoteActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/main/MainActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/ItemAdapter.java
  app/src/main/java/it/niedermann/owncloud/notes/main/items/NoteViewHolder.java
  app/src/main/java/it/niedermann/owncloud/notes/manageaccounts/ManageAccountsActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/preferences/PreferencesActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/share/NoteShareActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/share/NoteShareDetailActivity.kt
  app/src/main/java/it/niedermann/owncloud/notes/share/adapter/QuickSharingPermissionsAdapter.kt
  app/src/main/java/it/niedermann/owncloud/notes/share/adapter/ShareeListAdapter.java
  app/src/main/java/it/niedermann/owncloud/notes/share/adapter/holder/InternalShareViewHolder.java
  app/src/main/java/it/niedermann/owncloud/notes/share/dialog/QuickSharingPermissionsBottomSheetDialog.java
  app/src/main/res/drawable/ic_checkbox_blank_outline.xml
  app/src/main/res/drawable/ic_checkbox_marked.xml
  app/src/main/res/drawable/ic_delete_white_24dp.xml
  app/src/main/res/layout/activity_note_share.xml
  app/src/main/res/layout/item_add_public_share.xml
  app/src/main/res/layout/item_internal_share_link.xml
  app/src/main/res/layout/item_note_share_action.xml
  app/src/main/res/layout/item_notes_list_note_item_grid.xml
  app/src/main/res/layout/item_notes_list_note_item_grid_only_title.xml
  app/src/main/res/layout/item_notes_list_note_item_with_excerpt.xml
  app/src/main/res/layout/item_notes_list_note_item_without_excerpt.xml
  app/src/main/res/layout/item_notes_list_section_item.xml
  app/src/main/res/layout/quick_sharing_permissions_bottom_sheet_fragment.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review

#2756 Update Common Lib
  app/build.gradle
  app/src/main/java/it/niedermann/owncloud/notes/branding/BrandedActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/branding/BrandedFragment.kt
  app/src/main/java/it/niedermann/owncloud/notes/exception/ExceptionActivity.java
  app/src/main/java/it/niedermann/owncloud/notes/importaccount/ImportAccountActivity.java
  gradle/verification-metadata.xml
Labels: 3. to review, backport-request

#2758 Note NPE Check
  app/src/main/java/it/niedermann/owncloud/notes/edit/BaseNoteFragment.java
Labels: 3. to review, backport-request
